development: &development
  adapter: mysql2
  encoding: utf8
  # host: 192.168.1.200
  host: localhost
  reconnect: false
  database: live
  pool: 5
  username: root
  password: '123456'
  reconnect: true

production:
  <<: *development